In [2]:
import numpy as np

In [3]:
np.random.randint(0,10)

4

In [4]:
np.random.randint(10,100,5)

array([98, 31, 98, 53, 23])

In [5]:
np.random.randn(5)

array([ 0.36277523, -0.59683269, -0.19735656,  0.04030355,  0.94048752])

In [6]:
np.random.randn(10)

array([-0.54211434,  1.06468119, -1.52573647,  0.46543074, -1.11282341,
        0.63215574,  0.06462144,  0.4875376 , -0.70975724,  1.77884424])